# us_locations.py - US states and cities data
from typing import Dict, List

US_STATES: List[str] = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI",
    "MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT",
    "VT","VA","WA","WV","WI","WY","DC"
]

STATE_TO_CITIES: Dict[str, List[str]] = {
    "AL": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
    "AK": ["Anchorage", "Fairbanks", "Juneau", "Sitka"],
    "AZ": ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"],
    "AR": ["Little Rock", "Fayetteville", "Fort Smith", "Springdale"],
    "CA": ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Oakland", "Fresno", "Irvine", "Palo Alto", "Santa Clara", "Los Gatos", "Mountain View"],
    "CO": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
    "CT": ["Bridgeport", "New Haven", "Stamford", "Hartford", "Norwalk"],
    "DE": ["Wilmington", "Dover", "Newark"],
    "FL": ["Miami", "Tampa", "Orlando", "Jacksonville", "Tallahassee", "Fort Lauderdale"],
    "GA": ["Atlanta", "Savannah", "Augusta", "Athens", "Macon"],
    "HI": ["Honolulu", "Hilo", "Kailua", "Kaneohe"],
    "ID": ["Boise", "Idaho Falls", "Meridian", "Twin Falls"],
    "IL": ["Chicago", "Aurora", "Naperville", "Peoria", "Evanston"],
    "IN": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
    "IA": ["Des Moines", "Cedar Rapids", "Davenport", "Iowa City"],
    "KS": ["Wichita", "Overland Park", "Kansas City", "Topeka"],
    "KY": ["Louisville", "Lexington", "Bowling Green", "Covington"],
    "LA": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
    "ME": ["Portland", "Bangor", "Augusta"],
    "MD": ["Baltimore", "Silver Spring", "Rockville", "Bethesda"],
    "MA": ["Boston", "Cambridge", "Worcester", "Springfield", "Somerville"],
    "MI": ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"],
    "MN": ["Minneapolis", "Saint Paul", "Rochester", "Duluth"],
    "MS": ["Jackson", "Gulfport", "Hattiesburg"],
    "MO": ["Kansas City", "Saint Louis", "Springfield", "Columbia"],
    "MT": ["Billings", "Missoula", "Bozeman", "Helena"],
    "NE": ["Omaha", "Lincoln", "Bellevue"],
    "NV": ["Las Vegas", "Reno", "Henderson", "Carson City"],
    "NH": ["Manchester", "Nashua", "Concord"],
    "NJ": ["Newark", "Jersey City", "Paterson", "Hoboken"],
    "NM": ["Albuquerque", "Santa Fe", "Las Cruces"],
    "NY": ["New York", "Buffalo", "Rochester", "Albany", "Syracuse", "White Plains"],
    "NC": ["Charlotte", "Raleigh", "Durham", "Greensboro"],
    "ND": ["Fargo", "Bismarck", "Grand Forks"],
    "OH": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Dayton"],
    "OK": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    "OR": ["Portland", "Eugene", "Salem", "Bend"],
    "PA": ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown"],
    "RI": ["Providence", "Warwick", "Cranston"],
    "SC": ["Charleston", "Columbia", "Greenville"],
    "SD": ["Sioux Falls", "Rapid City"],
    "TN": ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
    "TX": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "Plano", "Irving"],
    "UT": ["Salt Lake City", "Provo", "Ogden", "St. George"],
    "VT": ["Burlington", "Montpelier"],
    "VA": ["Arlington", "Alexandria", "Richmond", "Norfolk", "Reston"],
    "WA": ["Seattle", "Spokane", "Tacoma", "Bellevue", "Redmond"],
    "WV": ["Charleston", "Morgantown", "Huntington"],
    "WI": ["Milwaukee", "Madison", "Green Bay"],
    "WY": ["Cheyenne", "Casper", "Laramie"],
    "DC": ["Washington"],
}
